name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # 设置你的主分支名称，如主分支不是 main，需要修改

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v2
    - name: Build and Deploy to Azure Static Web Apps
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}  # 自动创建的 token，用于 GitHub 操作
        action: "upload"
        app_location: "/"  # React 应用在仓库中的路径，根路径为 "/"
        api_location: "api"  # 如果有 API 的话，可以指定 API 的路径
        output_location: "build"  # React 应用构建后的输出路径，默认为 build
